edit html and css
aakbarkhan/Hello-Microverse pull request #1
Opened 2021-09-16 02:31 UTC by aakbarkhan

2021-09-16 07:24 UTC, wandji20 requested changes
Hello, @aakbarkhan  
-----
Great :muscle:  job :raised_hands:  implementing most of the requirements for Hello Microverse.
However, there are a few issues you need to address to have this project approved.
## To Highlight! :clap:  :green_circle: 

:heavy_check_mark: All linter checks are passing.
:heavy_check_mark: Commit messages are descriptive.

## Status: Require Changes :recycle: :red_circle: 
Please check the comments below and under the review and make all required changes.
Submit for a re-review once you are ready!
- [x] Pull Request should have a summary describing introduced changes in more details

- [x] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section') instead of microverse

- [x] Files that are irrelevant to run this project should be ignored (eg .hintrc, .stylelintrc.json, etc)

**Happy coding :computer:** 
**_Do not hesitate to make comments in this PR in case of doubts._**
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 07:24 UTC, wandji20 commented on MIT.md
> +THE [APP TYPE] IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEM
- [ ] It will be nice to customize this license.

2021-09-17 07:10 UTC, DanteAlonsoHT approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @aakbarkhan,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 07:10 UTC, DanteAlonsoHT commented on MIT.md
> +## Copyright 2021, [YOUR NAME]
- [ ] [OPTIONAL] Instead of `[YOUR NAME]` you can add your name there.

2021-09-17 07:10 UTC, DanteAlonsoHT commented on README.md
> +Hello Microverse project.
- [ ] [OPTIONAL] For the next projects you should add a better description, just try to explain what you did, what is the main scope, what kind of technologies or techniques you used, and so on. (Add like 3 lines or more at least in your description from your README file for the next time 😉).

2021-09-17 08:05 UTC, merged